/**
 * projects.tsx — DO NOT EDIT THIS FILE for content changes.
 *
 * To update project content (title, description, links, skills):
 *   → Edit  src/data/projects-data.ts  only
 *
 * This file reads from projects-data.ts and converts it into the
 * shape the rest of the app expects. UI / animations stay untouched.
 */

import AceTernityLogo from "@/components/logos/aceternity";
import SlideShow from "@/components/slide-show";
import { Button } from "@/components/ui/button";
import { TypographyH3, TypographyP } from "@/components/ui/typography";
import { ArrowUpRight } from "lucide-react";
import Link from "next/link";
import { ReactNode } from "react";
import { RiNextjsFill, RiNodejsFill, RiReactjsFill } from "react-icons/ri";
import {
  SiChakraui,
  SiDocker,
  SiExpress,
  SiFirebase,
  SiJavascript,
  SiMongodb,
  SiPostgresql,
  SiPrisma,
  SiPython,
  SiReactquery,
  SiSanity,
  SiShadcnui,
  SiSocketdotio,
  SiSupabase,
  SiTailwindcss,
  SiThreedotjs,
  SiTypescript,
  SiVuedotjs,
  SiVite,
  SiNetlify,
  SiHtml5,
  SiCss3,
  SiBootstrap,
} from "react-icons/si";
import { TbBrandFramerMotion } from "react-icons/tb";
import projectsData from "./projects.json";

// ─── Types ────────────────────────────────────────────────────
export type Skill = {
  title: string;
  bg: string;
  fg: string;
  icon: ReactNode;
};

export type Project = {
  id: string;
  category: string;
  title: string;
  src: string;
  screenshots: string[];
  skills: { frontend: Skill[]; backend: Skill[] };
  content: React.ReactNode | any;
  github?: string;
  live: string;
};

// ─── Skill chips map ──────────────────────────────────────────
// Add more entries here if you add new skills to projects-data.ts
const PROJECT_SKILLS: Record<string, Skill> = {
  next: { title: "Next.js",        bg: "black", fg: "white", icon: <RiNextjsFill /> },
  node: { title: "Node.js",        bg: "black", fg: "white", icon: <RiNodejsFill /> },
  react: { title: "React.js",      bg: "black", fg: "white", icon: <RiReactjsFill /> },
  ts: { title: "TypeScript",       bg: "black", fg: "white", icon: <SiTypescript /> },
  js: { title: "JavaScript",       bg: "black", fg: "white", icon: <SiJavascript /> },
  python: { title: "Python",       bg: "black", fg: "white", icon: <SiPython /> },
  tailwind: { title: "Tailwind",   bg: "black", fg: "white", icon: <SiTailwindcss /> },
  supabase: { title: "Supabase",   bg: "black", fg: "white", icon: <SiSupabase /> },
  postgres: { title: "PostgreSQL", bg: "black", fg: "white", icon: <SiPostgresql /> },
  mongo: { title: "MongoDB",       bg: "black", fg: "white", icon: <SiMongodb /> },
  express: { title: "Express",     bg: "black", fg: "white", icon: <SiExpress /> },
  docker: { title: "Docker",       bg: "black", fg: "white", icon: <SiDocker /> },
  firebase: { title: "Firebase",   bg: "black", fg: "white", icon: <SiFirebase /> },
  vite: { title: "Vite",           bg: "black", fg: "white", icon: <SiVite /> },
  vue: { title: "Vue.js",          bg: "black", fg: "white", icon: <SiVuedotjs /> },
  prisma: { title: "Prisma",       bg: "black", fg: "white", icon: <SiPrisma /> },
  sanity: { title: "Sanity",       bg: "black", fg: "white", icon: <SiSanity /> },
  spline: { title: "Spline",       bg: "black", fg: "white", icon: <SiThreedotjs /> },
  framerMotion: { title: "Framer Motion", bg: "black", fg: "white", icon: <TbBrandFramerMotion /> },
  shadcn: { title: "ShadCN UI",    bg: "black", fg: "white", icon: <SiShadcnui /> },
  netlify: { title: "Netlify",     bg: "black", fg: "white", icon: <SiNetlify /> },
  html: { title: "HTML5",          bg: "black", fg: "white", icon: <SiHtml5 /> },
  css: { title: "CSS3",            bg: "black", fg: "white", icon: <SiCss3 /> },
  bootstrap: { title: "Bootstrap", bg: "black", fg: "white", icon: <SiBootstrap /> },
  openai: {
    title: "OpenAI",
    bg: "black",
    fg: "white",
    icon: <img src="/assets/icons/openai-svgrepo-com_white.svg" alt="OpenAI" className="w-4 h-4" />,
  },
  aceternity: { title: "Aceternity", bg: "black", fg: "white", icon: <AceTernityLogo /> },
};

// ─── Links component ──────────────────────────────────────────
const ProjectsLinks = ({ live, repo }: { live: string; repo?: string }) => (
  <div className="flex flex-col md:flex-row items-center justify-start gap-3 my-3 mb-8">
    <Link className="font-mono underline flex gap-2" rel="noopener" target="_new" href={live}>
      <Button variant={"default"} size={"sm"}>
        Visit Website
        <ArrowUpRight className="ml-3 w-5 h-5" />
      </Button>
    </Link>
    {repo && (
      <Link className="font-mono underline flex gap-2" rel="noopener" target="_new" href={repo}>
        <Button variant={"default"} size={"sm"}>
          Github
          <ArrowUpRight className="ml-3 w-5 h-5" />
        </Button>
      </Link>
    )}
  </div>
);

// ─── Convert projects-data.ts → Project[] ────────────────────
// This auto-generates the content JSX from plain text data.
// You never need to touch this — just edit projects-data.ts.
const projects: Project[] = projectsData.map((p) => {
  const resolveSkill = (key: string): Skill =>
    PROJECT_SKILLS[key] ?? { title: key, bg: "black", fg: "white", icon: null };

  return {
    id: p.id,
    category: p.category,
    title: p.title,
    src: p.imageSrc,
    screenshots: [p.imageSrc],
    live: p.live,
    github: p.github,
    skills: {
      frontend: p.skills.map(resolveSkill),
      backend: [],
    },
    get content() {
      return (
        <div>
          <TypographyP className="font-mono">{p.description}</TypographyP>
          <ProjectsLinks live={p.live} repo={p.github} />
          {p.highlights.map((section) => (
            <div key={section.heading}>
              <TypographyH3 className="my-4 mt-8">{section.heading}</TypographyH3>
              <ul className="list-disc ml-6 mb-4 space-y-1">
                {section.points.map((point, i) => (
                  <li key={i} className="font-mono text-sm">
                    {point}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      );
    },
  };
});

export default projects;
